### ISSUE TITLE
Webcam blocked (HTTPS required)

### ISSUE THREAD

**Issue by cr0bar** [muaz-khan/WebRTC-Experiment#585]
It seems that Chrome is blocking webcam access on the 'video-conferencing' example as by default it doesn't use HTTPS. There doesn't seem to be a simple way to flip between HTTP and HTTPS.

**Comment by muaz-khan** [comment]
It will work on localhost. You can copy html demo file and run on any HTTPs server e.g. github pages, dropbox, google drive, etc. Github pages is the best/easiest solution.

HTML demo file can be copied to any web server (PHP/python/etc.).

You can run it on heroku as well. Heroku comes with builtin HTTPs server.

Otherwise, if you want to use a nodejs hosting, then please download this repo:

* https://github.com/muaz-khan/WebRTC-Experiment/tree/master/socketio-over-nodejs

Copy video-conferencing HTML file and paste into `static` directory here:

* https://github.com/muaz-khan/WebRTC-Experiment/tree/master/socketio-over-nodejs/static

Now run [`signaler-ssl.js`](https://github.com/muaz-khan/WebRTC-Experiment/blob/master/socketio-over-nodejs/signaler-ssl.js) file:

```sh
node signaler-ssl.js

# or 
nohup node signaler-ssl.js &
```

See how to set valid SSL certiicatates (eg. that are issued by lets-encrypt/etc):

* https://github.com/muaz-khan/WebRTC-Experiment/issues/62#issuecomment-20981138

**Comment by cr0bar** [comment]
Thank you for such a complete answer.
